version: '3'
services:
    my_python_app:
        container_name: my_python_app
        build: ./src
    my_python_app2:
        container_name: my_python_app2
        build: ./src
    nginx:
        build: ./nginx
        #image: nginx
        #volumes:
        #  - ./nginx:/etc/nginx/conf.d
        ports:
          - "80:80"
        depends_on:
          - my_python_app
          - my_python_app2
