version: '3'
services:
    my_python_app:
        container_name: my_python_app
        build: .
    my_python_app2:
        container_name: my_python_app2
        build: .
    nginx:
        build: .
        #image: nginx
        #volumes:
        #  - ./nginx:/etc/nginx/conf.d
        ports:
          - "80:80"
        depends_on:
          - my_python_app
          - my_python_app2
