jobs:
  build:
    machine:
      image: ubuntu-2004:2023.04.2
    environment:
      DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1099606775000473660/4wymFPfjJzuMUf6MCK1c556LXGq_Ce8QnVYU90ydNUHGe0ZRWMQ0JBm8AkoAbNTqwBIt"
    steps:
      - checkout
      - run:
          name: Update apt packages
          command: sudo apt-get update
      - run:
          name: Build and start Docker containers
          command: docker compose up --build -d
      - run:
          name: Create log file
          command: cd src/ && touch app.log
      - run:
          name: Install Python dependencies
          command: cd src/ && pip3 install --no-cache-dir -r requirements.txt
      - run:
          name: Run Selenium tests
          command: cd src/ && python3 seleniumunit.py
      - run:
          name: Notify Discord of test results
          when: always
          command: |
            if [ "$CIRCLE_TEST_RESULT" == "0" ]; then
              curl -X POST -H 'Content-Type: application/json' -d '{"content": "Selenium tests passed!"}' $DISCORD_WEBHOOK
            else
              curl -X POST -H 'Content-Type: application/json' -d '{"content": "Selenium Tests failed!"}' $DISCORD_WEBHOOK
      - run:
          name: Log in to Docker registry
          command: docker login -u $GITLAB_USER -p $ACCESS_TOKEN registry.gitlab.com
      - run:
          name: Build and push Docker image
          command: docker build -t registry.gitlab.com/ariyonzor/circleci:$CIRCLE_BUILD_NUM /home/circleci/project/src/ && docker push registry.gitlab.com/ariyonzor/circleci:$CIRCLE_BUILD_NUM
      - run:
          name: Create AWS credentials and config files
          command: |
            cd ~ && mkdir .aws && cd .aws && touch credentials && touch config
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "[default]" > ~/.aws/config
            echo "region = us-east-1" >> ~/.aws/config
      - run:
          name: Run Checkov tests
          command: cd terraform-configuration/ && checkov -d .
      - run:
          name: Notify Discord of Checkov test results
          when: always
          command: |
            if [ "$CIRCLE_TEST_RESULT" == "0" ]; then
              curl -X POST -H 'Content-Type: application/json' -d '{"content": "Checkov tests passed!"}' $DISCORD_WEBHOOK
            else
              curl -X POST -H 'Content-Type: application/json' -d '{"content": "Checkov tests failed!"}' $DISCORD_WEBHOOK
