version: 2.1

orbs:
  discord: circleci/discord@1.0.3

jobs:
  build:
    docker:
      - image: circleci/python:3.9.1-buster
    steps:
      - checkout
      - run:
          name: Build and Test Docker Image
          command: |
            sudo docker-compose up --build -d
      - run:
          name: Run Check Application Test
          command: |
            python3 checkapplication.py
    parallelism: 1

  selenium_test:
    docker:
      - image: circleci/python:3.9.1-buster
      - image: circleci/selenium:3.141.59-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium
            pip3 install selenium
      - run:
          name: Run Selenium Test
          command: |
            python3 seleniumunit.py
    parallelism: 1

workflows:
  build_and_test:
    jobs:
      - build
      - selenium_test:
          requires:
            - build
          filters:
            branches:
              only:
                - main

  push_image:
    jobs:
      - build:
          requires:
            - selenium_test
      - discord/notify:
          requires:
            - build
