version: 2.1

orbs:
  docker: circleci/docker@1.2.3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build Docker images
          command: |
            docker-compose up --build -d
      - run:
          name: Run Unit tests
          command: |
            python3 checkapplication.py
      - run:
          name: Run Selenium tests
          command: |
            python3 seleniumunit.py
    # notify on Slack or Discord about test results
    - notify:
        name: Test Results
        channels:
          - '#general'
        message: |
          Tests Passed

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker images to registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag web_nginx arieldomchik/ariel:nginx
            docker tag web_my_python_app arieldomchik/ariel:webapp
            docker tag web_my_python_app2 arieldomchik/ariel:webapp
            docker commit web_nginx_1 arieldomchik/ariel:nginx
            docker commit my_python_app arieldomchik/ariel:webapp
            docker commit my_python_app2 arieldomchik/ariel:webapp
            docker push arieldomchik/ariel:nginx
            docker push arieldomchik/ariel:webapp
            docker push arieldomchik/ariel:webapp

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
