jobs:
  build:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      - run: sudo apt-get update 
      - run: ls && docker compose up --build -d
      - run: python3 /src/checkapplication.py
