jobs:
  build:
    machine:
      image: ubuntu-2004:2023.04.2
    environment:
      DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1099606775000473660/4wymFPfjJzuMUf6MCK1c556LXGq_Ce8QnVYU90ydNUHGe0ZRWMQ0JBm8AkoAbNTqwBIt"
    steps:
      - checkout
      - run: sudo apt-get update 
      - run: ls && docker compose up --build -d
      - run: cd src/ && touch app.log
      - run: cd src/ && pip3 install --no-cache-dir -r requirements.txt
      - run: cd src/ && python3 seleniumunit.py
      - run: echo "CIRCLE_TEST_RESULT=$?" >> $BASH_ENV
      - run:
          name: Notify Discord
          command: |
            if [ "$CIRCLE_TEST_RESULT" == "0" ]; then
              curl -X POST -H 'Content-Type: application/json' -d '{"content": "All tests passed!"}' $DISCORD_WEBHOOK
            else
              curl -X POST -H 'Content-Type: application/json' -d '{"content": "Tests failed!"}' $DISCORD_WEBHOOK
            fi
          when: always
      - run: docker login -u $GITLAB_USER -p $ACCESS_TOKEN registry.gitlab.com
      - run: docker build -t docker build -t registry.gitlab.com/ariyonzor/circleci /home/circleci/project/src/
      - run: docker push registry.gitlab.com/ariyonzor/circleci
